version: '3'
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306:3306
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    container_name: "rails_api"
    depends_on:
      - db
    environment:
      - ENV_MODE=dev
      - MYSQL_CONTAINER_NAME=buzziee_mysql
    ports:
      - $PORT:3000
    volumes:
      - ./src:/usr/src/app
    command: ["rails", "server", "-b", "0.0.0.0"]
    tty: true
