version: '3'
services:
  mysql:
    image: mysql:8.0.23
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - $MYSQL_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: rails_api_mysql
  app:
    container_name: "rails_api"
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - mysql
    environment:
      - ENV_MODE=dev
      - MYSQL_CONTAINER_NAME=rails_api_mysql
    ports:
      - $PORT:3000
    volumes:
      - ./src:/usr/src/app
    command: ["rails", "server", "-b", "0.0.0.0"]
    tty: true
